"""
FinAI Excel Exporter — Professional White Theme (Big 4 Style)
Row format: {c, l, ac, pl, lvl, bold, sep, s}
Clean white background, navy headers, proper borders, print-ready layout.
Bilingual support (EN/KA).
"""
from pathlib import Path
from datetime import datetime
from typing import Any, Optional
from app.config import settings
import logging

logger = logging.getLogger(__name__)

# ── Georgian Header Translations ─────────────────────────────────
HEADER_I18N = {
    'en': {
        'Code': 'Code', 'Line Item': 'Line Item', 'Actual': 'Actual',
        'Budget/Plan': 'Budget/Plan', 'Variance': 'Variance', 'Var %': 'Var %',
        'Net Revenue': 'Net Revenue', 'Gross Margin': 'Gross Margin',
        'EBITDA': 'EBITDA', 'Net Profit': 'Net Profit', 'OpEx': 'OpEx',
        'Date': 'Date', 'Type': 'Type', 'Department': 'Department',
        'Category': 'Category', 'Counterparty': 'Counterparty',
        'Amount': 'Amount', 'VAT': 'VAT', 'Acct Dr': 'Acct Dr', 'Acct Cr': 'Acct Cr',
        'Item': 'Item', 'Total Assets': 'Total Assets',
        'Total Liabilities': 'Total Liabilities', 'Equity': 'Equity',
        'BS Equation Check': 'BS Equation Check',
        'Assets - (Liabilities + Equity)': 'Assets - (Liabilities + Equity)',
        'BALANCED': 'BALANCED ✓', 'IMBALANCED': 'IMBALANCED ✗',
        'Generated by FinAI': 'Generated by FinAI',
        'Period': 'Period', 'Currency': 'Currency',
        'ASSETS': 'ASSETS', 'LIABILITIES': 'LIABILITIES', 'EQUITY': 'EQUITY',
    },
    'ka': {
        'Code': 'კოდი', 'Line Item': 'სტატია', 'Actual': 'ფაქტობრივი',
        'Budget/Plan': 'ბიუჯეტი/გეგმა', 'Variance': 'გადახრა', 'Var %': 'გადახრა %',
        'Net Revenue': 'წმინდა შემოსავალი', 'Gross Margin': 'მთლიანი მარჟა',
        'EBITDA': 'ებითდა', 'Net Profit': 'წმინდა მოგება', 'OpEx': 'საოპერაციო',
        'Date': 'თარიღი', 'Type': 'ტიპი', 'Department': 'დეპარტამენტი',
        'Category': 'კატეგორია', 'Counterparty': 'კონტრაგენტი',
        'Amount': 'თანხა', 'VAT': 'დღგ', 'Acct Dr': 'ანგ. დებეტი', 'Acct Cr': 'ანგ. კრედიტი',
        'Item': 'სტატია', 'Total Assets': 'აქტივები სულ',
        'Total Liabilities': 'ვალდებულებები სულ', 'Equity': 'კაპიტალი',
        'BS Equation Check': 'ბალანსის ტოლობის შემოწმება',
        'Assets - (Liabilities + Equity)': 'აქტივები - (ვალდებულებები + კაპიტალი)',
        'BALANCED': 'ბალანსირებულია ✓', 'IMBALANCED': 'არ ბალანსდება ✗',
        'Generated by FinAI': 'შექმნილია FinAI-ის მიერ',
        'Period': 'პერიოდი', 'Currency': 'ვალუტა',
        'ASSETS': 'აქტივები', 'LIABILITIES': 'ვალდებულებები', 'EQUITY': 'კაპიტალი',
    }
}


class ExcelExporter:
    def __init__(self, export_dir: str = "./exports"):
        self.export_dir = Path(export_dir)
        self.export_dir.mkdir(exist_ok=True)

    # ── Professional Color Palette (Big 4 Style) ─────────────────
    WHITE       = "FFFFFF"
    LIGHT_GRAY  = "F2F2F2"
    HEADER_BLUE = "4472C4"
    SECTION_BG  = "D6E4F0"
    TOTAL_BG    = "E2EFDA"
    DARK_TEXT   = "1F2937"
    MUTED_TEXT  = "6B7280"
    RED_TEXT    = "DC2626"
    GREEN_TEXT  = "059669"
    BORDER_CLR  = "B4C6E7"
    LOGO_BG     = "1F4E79"

    def _tr(self, text: str, language: str = 'en') -> str:
        """Translate a header/label string."""
        return HEADER_I18N.get(language, HEADER_I18N['en']).get(text, text)

    def export_report(self, report: Any, language: str = 'en') -> str:
        """Export a Report model instance to professionally styled Excel."""
        try:
            from openpyxl import Workbook
            from openpyxl.styles import (PatternFill, Font, Alignment, Border, Side,
                                          numbers)
            from openpyxl.utils import get_column_letter
        except ImportError:
            raise RuntimeError("openpyxl not installed: pip install openpyxl")

        # Extract language from report metadata if available
        if hasattr(report, 'metadata_json') and report.metadata_json:
            import json
            try:
                meta = report.metadata_json if isinstance(report.metadata_json, dict) else json.loads(report.metadata_json)
                if isinstance(meta, str):
                    meta = json.loads(meta)  # handle double-encoded
                language = meta.get('language', language)
            except Exception:
                pass

        tr = lambda text: self._tr(text, language)
        wb = Workbook()
        ws = wb.active
        ws.title = report.report_type.upper()

        # ── Style helpers ────────────────────────────────────────
        def fill(hex_color):
            return PatternFill("solid", fgColor=hex_color)

        def font(color=None, bold=False, size=11, name="Calibri"):
            return Font(color=color or self.DARK_TEXT, bold=bold, size=size, name=name)

        def align(h="left", v="center", wrap=False, indent=0):
            return Alignment(horizontal=h, vertical=v, wrap_text=wrap, indent=indent)

        thin_border = Border(
            bottom=Side(style="thin", color=self.BORDER_CLR),
            top=Side(style="thin", color=self.BORDER_CLR),
            left=Side(style="thin", color=self.BORDER_CLR),
            right=Side(style="thin", color=self.BORDER_CLR),
        )
        total_border = Border(
            top=Side(style="thin", color=self.DARK_TEXT),
            bottom=Side(style="double", color=self.DARK_TEXT),
            left=Side(style="thin", color=self.BORDER_CLR),
            right=Side(style="thin", color=self.BORDER_CLR),
        )
        section_border = Border(
            bottom=Side(style="medium", color=self.HEADER_BLUE),
            left=Side(style="thin", color=self.BORDER_CLR),
            right=Side(style="thin", color=self.BORDER_CLR),
        )

        # ── Column widths ────────────────────────────────────────
        ws.column_dimensions["A"].width = 10
        ws.column_dimensions["B"].width = 44
        ws.column_dimensions["C"].width = 18
        ws.column_dimensions["D"].width = 18
        ws.column_dimensions["E"].width = 16
        ws.column_dimensions["F"].width = 12

        # ── HEADER BLOCK ─────────────────────────────────────────
        row = 1
        ws.row_dimensions[row].height = 8
        for col in range(1, 7):
            ws.cell(row=row, column=col).fill = fill(self.WHITE)

        row = 2
        ws.row_dimensions[row].height = 28
        ws.merge_cells(f"A{row}:F{row}")
        c = ws[f"A{row}"]
        c.value = report.company or settings.COMPANY_NAME
        c.font = font(self.LOGO_BG, bold=True, size=14)
        c.fill = fill(self.WHITE)
        c.alignment = align("left")

        row = 3
        ws.row_dimensions[row].height = 22
        ws.merge_cells(f"A{row}:F{row}")
        c = ws[f"A{row}"]
        c.value = report.title
        c.font = font(self.HEADER_BLUE, bold=True, size=12)
        c.fill = fill(self.WHITE)
        c.alignment = align("left")

        row = 4
        ws.row_dimensions[row].height = 16
        ws.merge_cells(f"A{row}:C{row}")
        ws[f"A{row}"].value = f"{tr('Period')}: {report.period or '—'}"
        ws[f"A{row}"].font = font(self.MUTED_TEXT, size=10)
        ws[f"A{row}"].fill = fill(self.WHITE)
        ws.merge_cells(f"D{row}:F{row}")
        ws[f"D{row}"].value = f"{tr('Currency')}: {report.currency or 'GEL'}"
        ws[f"D{row}"].font = font(self.MUTED_TEXT, size=10)
        ws[f"D{row}"].fill = fill(self.WHITE)
        ws[f"D{row}"].alignment = align("right")

        row = 5
        ws.row_dimensions[row].height = 6
        for col in range(1, 7):
            ws.cell(row=row, column=col).fill = fill(self.WHITE)
            ws.cell(row=row, column=col).border = Border(
                bottom=Side(style="medium", color=self.HEADER_BLUE))

        # ── KPI SUMMARY ──────────────────────────────────────────
        if report.kpis:
            row = 6
            ws.row_dimensions[row].height = 20
            kpi_headers = [tr("Net Revenue"), tr("Gross Margin"), tr("EBITDA"),
                          tr("Net Profit"), tr("OpEx")]
            kpi_keys = ["revenue", "gross_margin", "ebitda", "net_profit", "opex"]
            for j, (h, k) in enumerate(zip(kpi_headers, kpi_keys)):
                col = j + 1
                lbl = ws.cell(row=row, column=col)
                lbl.value = h
                lbl.font = font(self.MUTED_TEXT, size=9)
                lbl.fill = fill(self.SECTION_BG)
                lbl.alignment = align("center")
                lbl.border = thin_border

                row2 = 7
                ws.row_dimensions[row2].height = 22
                val = ws.cell(row=row2, column=col)
                v = report.kpis.get(k, 0) or 0
                val.value = v
                val.number_format = '#,##0'
                val.font = font(self.GREEN_TEXT if v >= 0 else self.RED_TEXT, bold=True, size=11)
                val.fill = fill(self.WHITE)
                val.alignment = align("center")
                val.border = thin_border

            row = 8
            ws.row_dimensions[row].height = 6
            for col in range(1, 7):
                ws.cell(row=row, column=col).fill = fill(self.WHITE)

        # ── COLUMN HEADERS ───────────────────────────────────────
        header_row = 9 if report.kpis else 6
        ws.row_dimensions[header_row].height = 22
        headers = [tr("Code"), tr("Line Item"), tr("Actual"),
                  tr("Budget/Plan"), tr("Variance"), tr("Var %")]
        for j, h in enumerate(headers):
            c = ws.cell(row=header_row, column=j + 1)
            c.value = h
            c.font = font("FFFFFF", bold=True, size=10)
            c.fill = fill(self.HEADER_BLUE)
            c.alignment = align("center" if j >= 2 else "left")
            c.border = thin_border

        # ── DATA ROWS ────────────────────────────────────────────
        row = header_row + 1
        alt = False  # alternating row toggle
        curr = report.currency or "GEL"

        for item in (report.rows or []):
            if not isinstance(item, dict):
                continue
            ws.row_dimensions[row].height = 18

            lvl = item.get("lvl", item.get("level", 0)) or 0
            bold = item.get("bold", False)
            sep = item.get("sep", False)
            code = item.get("c", item.get("code", ""))
            label = item.get("l", item.get("label", ""))
            ac = item.get("ac", item.get("actual", 0)) or 0
            pl = item.get("pl", item.get("plan", 0)) or 0
            var = ac - pl if pl else 0
            var_pct = var / abs(pl) * 100 if pl else 0

            # Determine row style
            if sep:
                bg = self.SECTION_BG
                fc = self.HEADER_BLUE
                brd = section_border
            elif bold and lvl == 0:
                bg = self.TOTAL_BG
                fc = self.DARK_TEXT
                brd = total_border
            else:
                bg = self.LIGHT_GRAY if alt else self.WHITE
                fc = self.DARK_TEXT
                brd = thin_border
                alt = not alt

            # Code column
            c0 = ws.cell(row=row, column=1, value=code)
            c0.font = font(self.MUTED_TEXT, size=9)
            c0.fill = fill(bg)
            c0.alignment = align("center")
            c0.border = brd

            # Label column (with indentation)
            c1 = ws.cell(row=row, column=2, value=label)
            c1.font = font(fc, bold=bold or sep, size=10 if sep else 10)
            c1.fill = fill(bg)
            c1.alignment = align("left", indent=lvl)
            c1.border = brd

            # Actual column
            c2 = ws.cell(row=row, column=3, value=ac if ac else None)
            c2.number_format = '#,##0;[Red](#,##0)'
            c2.font = font(self.RED_TEXT if ac < 0 else fc, bold=bold)
            c2.fill = fill(bg)
            c2.alignment = align("right")
            c2.border = brd

            # Plan column
            c3 = ws.cell(row=row, column=4, value=pl if pl else None)
            c3.number_format = '#,##0'
            c3.font = font(self.MUTED_TEXT)
            c3.fill = fill(bg)
            c3.alignment = align("right")
            c3.border = brd

            # Variance
            c4 = ws.cell(row=row, column=5, value=var if pl else None)
            c4.number_format = '#,##0;[Red](#,##0)'
            c4.font = font(self.GREEN_TEXT if var >= 0 else self.RED_TEXT)
            c4.fill = fill(bg)
            c4.alignment = align("right")
            c4.border = brd

            # Var %
            c5 = ws.cell(row=row, column=6, value=round(var_pct, 1) if pl else None)
            c5.number_format = '0.0"%"'
            c5.font = font(self.GREEN_TEXT if var_pct >= 0 else self.RED_TEXT, size=9)
            c5.fill = fill(bg)
            c5.alignment = align("right")
            c5.border = brd

            row += 1

        last_data_row = row - 1

        # ── FOOTER ───────────────────────────────────────────────
        row += 1
        ws.merge_cells(f"A{row}:F{row}")
        c = ws.cell(row=row, column=1)
        c.value = f"{tr('Generated by FinAI')} · {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        c.font = font(self.MUTED_TEXT, size=9)
        c.fill = fill(self.WHITE)
        c.alignment = align("center")

        # ── Freeze panes (below header row) ──────────────────────
        ws.freeze_panes = f"A{header_row + 1}"

        # ── AutoFilter ───────────────────────────────────────────
        if last_data_row > header_row:
            ws.auto_filter.ref = f"A{header_row}:F{last_data_row}"

        # ── Print setup ──────────────────────────────────────────
        ws.page_setup.orientation = 'landscape'
        ws.page_setup.paperSize = ws.PAPERSIZE_A4
        ws.page_setup.fitToWidth = 1
        ws.page_setup.fitToHeight = 0
        ws.print_title_rows = f'{header_row}:{header_row}'
        ws.oddHeader.center.text = report.company or settings.COMPANY_NAME
        ws.oddFooter.center.text = "Page &P of &N"

        # ── Fill remaining empty cells white ─────────────────────
        for r in range(1, row + 1):
            for col in range(1, 7):
                cell = ws.cell(row=r, column=col)
                if cell.fill.fill_type == "none":
                    cell.fill = fill(self.WHITE)

        fname = f"{report.report_type}_{report.period.replace(' ', '_')}_{report.id}.xlsx"
        path = str(self.export_dir / fname)
        wb.save(path)
        logger.info(f"Exported: {path}")
        return path

    def export_balance_sheet(self, report: Any, bs_data: dict = None, language: str = 'en') -> str:
        """Export Balance Sheet with equation validation row."""
        try:
            from openpyxl import Workbook
            from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
        except ImportError:
            raise RuntimeError("openpyxl not installed")

        # Extract language from report metadata if available
        if hasattr(report, 'metadata_json') and report.metadata_json:
            import json
            try:
                meta = report.metadata_json if isinstance(report.metadata_json, dict) else json.loads(report.metadata_json)
                if isinstance(meta, str):
                    meta = json.loads(meta)
                language = meta.get('language', language)
            except Exception:
                pass

        tr = lambda text: self._tr(text, language)
        wb = Workbook()
        ws = wb.active
        ws.title = "Balance Sheet"

        def fill(hex_color):
            return PatternFill("solid", fgColor=hex_color)
        def font(color=None, bold=False, size=11):
            return Font(color=color or self.DARK_TEXT, bold=bold, size=size, name="Calibri")
        def align(h="left", v="center", indent=0):
            return Alignment(horizontal=h, vertical=v, indent=indent)
        thin = Border(
            bottom=Side(style="thin", color=self.BORDER_CLR),
            top=Side(style="thin", color=self.BORDER_CLR),
            left=Side(style="thin", color=self.BORDER_CLR),
            right=Side(style="thin", color=self.BORDER_CLR))
        total_brd = Border(
            top=Side(style="thin", color=self.DARK_TEXT),
            bottom=Side(style="double", color=self.DARK_TEXT),
            left=Side(style="thin", color=self.BORDER_CLR),
            right=Side(style="thin", color=self.BORDER_CLR))

        ws.column_dimensions["A"].width = 44
        ws.column_dimensions["B"].width = 18
        ws.column_dimensions["C"].width = 14

        # Header
        row = 1
        ws.merge_cells(f"A{row}:C{row}")
        ws[f"A{row}"].value = report.company or settings.COMPANY_NAME
        ws[f"A{row}"].font = font(self.LOGO_BG, bold=True, size=14)
        ws[f"A{row}"].fill = fill(self.WHITE)
        row = 2
        ws.merge_cells(f"A{row}:C{row}")
        ws[f"A{row}"].value = report.title or tr("Item")
        ws[f"A{row}"].font = font(self.HEADER_BLUE, bold=True, size=12)
        ws[f"A{row}"].fill = fill(self.WHITE)
        row = 3
        ws[f"A{row}"].value = f"{tr('Period')}: {report.period or '—'}"
        ws[f"A{row}"].font = font(self.MUTED_TEXT, size=10)
        ws[f"A{row}"].fill = fill(self.WHITE)
        ws[f"C{row}"].value = f"{tr('Currency')}: {report.currency or 'GEL'}"
        ws[f"C{row}"].font = font(self.MUTED_TEXT, size=10)
        ws[f"C{row}"].fill = fill(self.WHITE)
        ws[f"C{row}"].alignment = align("right")
        row = 4
        for col in range(1, 4):
            ws.cell(row=row, column=col).border = Border(
                bottom=Side(style="medium", color=self.HEADER_BLUE))
            ws.cell(row=row, column=col).fill = fill(self.WHITE)
        ws.row_dimensions[row].height = 4

        # Write BS data using the standard rows format
        row = 5
        total_assets = 0
        total_liab = 0
        total_equity = 0

        for item in (report.rows or []):
            if not isinstance(item, dict):
                continue
            ws.row_dimensions[row].height = 18
            lvl = item.get("lvl", 0) or 0
            bold = item.get("bold", False)
            sep = item.get("sep", False)
            label = item.get("l", item.get("label", ""))
            ac = item.get("ac", item.get("actual", 0)) or 0

            if sep:
                bg = self.SECTION_BG
                fc = self.HEADER_BLUE
                brd = Border(bottom=Side(style="medium", color=self.HEADER_BLUE),
                            left=Side(style="thin", color=self.BORDER_CLR),
                            right=Side(style="thin", color=self.BORDER_CLR))
            elif bold and lvl == 0:
                bg = self.TOTAL_BG
                fc = self.DARK_TEXT
                brd = total_brd
            else:
                bg = self.WHITE
                fc = self.DARK_TEXT
                brd = thin

            # Track totals for equation check
            section = item.get("s", "")
            if section == "assets" and bold and lvl == 0:
                total_assets = ac
            elif section == "liabilities" and bold and lvl == 0:
                total_liab = ac
            elif section == "equity" and bold and lvl == 0:
                total_equity = ac

            c1 = ws.cell(row=row, column=1, value=label)
            c1.font = font(fc, bold=bold or sep)
            c1.fill = fill(bg)
            c1.alignment = align(indent=lvl)
            c1.border = brd

            c2 = ws.cell(row=row, column=2, value=ac if ac else None)
            c2.number_format = '#,##0;[Red](#,##0)'
            c2.font = font(self.RED_TEXT if ac < 0 else fc, bold=bold)
            c2.fill = fill(bg)
            c2.alignment = align("right")
            c2.border = brd

            c3 = ws.cell(row=row, column=3)
            c3.fill = fill(bg)
            c3.border = brd

            row += 1

        # ── BS EQUATION CHECK ────────────────────────────────────
        row += 1
        ws.row_dimensions[row].height = 6
        row += 1
        ws.merge_cells(f"A{row}:C{row}")
        ws[f"A{row}"].value = tr("BS Equation Check")
        ws[f"A{row}"].font = font(self.HEADER_BLUE, bold=True, size=11)
        ws[f"A{row}"].fill = fill(self.SECTION_BG)
        ws[f"A{row}"].border = Border(bottom=Side(style="medium", color=self.HEADER_BLUE))

        row += 1
        diff = total_assets - (total_liab + total_equity)
        balanced = abs(diff) < 1

        ws[f"A{row}"].value = tr("Assets - (Liabilities + Equity)")
        ws[f"A{row}"].font = font(self.DARK_TEXT, bold=True)
        ws[f"A{row}"].fill = fill(self.WHITE)
        ws[f"B{row}"].value = diff
        ws[f"B{row}"].number_format = '#,##0'
        ws[f"B{row}"].font = font(self.GREEN_TEXT if balanced else self.RED_TEXT, bold=True, size=12)
        ws[f"B{row}"].fill = fill(self.WHITE)
        ws[f"B{row}"].alignment = align("right")
        ws[f"C{row}"].value = tr("BALANCED") if balanced else tr("IMBALANCED")
        ws[f"C{row}"].font = font(self.GREEN_TEXT if balanced else self.RED_TEXT, bold=True)
        ws[f"C{row}"].fill = fill("E8F5E9" if balanced else "FFEBEE")

        # Footer
        row += 2
        ws.merge_cells(f"A{row}:C{row}")
        ws[f"A{row}"].value = f"{tr('Generated by FinAI')} · {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        ws[f"A{row}"].font = font(self.MUTED_TEXT, size=9)
        ws[f"A{row}"].alignment = align("center")

        # Print + freeze
        ws.freeze_panes = "A5"
        ws.page_setup.orientation = 'landscape'
        ws.page_setup.paperSize = ws.PAPERSIZE_A4
        ws.page_setup.fitToWidth = 1

        # Fill remaining white
        for r in range(1, row + 1):
            for col in range(1, 4):
                cell = ws.cell(row=r, column=col)
                if cell.fill.fill_type == "none":
                    cell.fill = fill(self.WHITE)

        fname = f"bs_{report.period.replace(' ', '_')}_{report.id}.xlsx"
        path = str(self.export_dir / fname)
        wb.save(path)
        logger.info(f"Exported BS: {path}")
        return path

    def export_report_with_provenance(self, report: Any, language: str = 'en') -> str:
        """Export report with Provenance sheet for traceability."""
        path = self.export_report(report, language=language)
        try:
            from openpyxl import load_workbook
            from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        except ImportError:
            raise RuntimeError("openpyxl not installed")

        wb = load_workbook(path)
        rows = report.rows or []
        provenance = []
        for idx, item in enumerate(rows, start=1):
            meta = item.get("meta") if isinstance(item, dict) else None
            tx_ids = []
            ds_ids = []
            if meta:
                tx = meta.get("tx_ids") or meta.get("transaction_ids")
                if isinstance(tx, list):
                    tx_ids = [str(x) for x in tx]
                ds = meta.get("dataset_id") or meta.get("source_dataset_id")
                if ds:
                    ds_ids = [str(ds)]
            if not tx_ids and isinstance(item, dict) and item.get("tx_ids"):
                tx_ids = [str(x) for x in item.get("tx_ids")]
            provenance.append({
                "row_index": idx,
                "code": item.get("c") if isinstance(item, dict) else None,
                "label": item.get("l") if isinstance(item, dict) else None,
                "dataset_ids": ",".join(ds_ids) if ds_ids else "",
                "tx_ids": ",".join(tx_ids) if tx_ids else "",
            })

        if provenance:
            ws = wb.create_sheet(title="Provenance")
            headers = ["Row", "Code", "Label", "Dataset IDs", "Transaction IDs"]
            for col, h in enumerate(headers, start=1):
                cell = ws.cell(row=1, column=col, value=h)
                cell.font = Font(color="FFFFFF", bold=True, name="Calibri")
                cell.fill = PatternFill("solid", fgColor=self.HEADER_BLUE)
                cell.alignment = Alignment(horizontal="center")
            for r, p in enumerate(provenance, start=2):
                ws.cell(row=r, column=1, value=p["row_index"])
                ws.cell(row=r, column=2, value=p["code"])
                ws.cell(row=r, column=3, value=p["label"])
                ws.cell(row=r, column=4, value=p["dataset_ids"])
                ws.cell(row=r, column=5, value=p["tx_ids"])
            ws.column_dimensions["A"].width = 8
            ws.column_dimensions["B"].width = 12
            ws.column_dimensions["C"].width = 40
            ws.column_dimensions["D"].width = 20
            ws.column_dimensions["E"].width = 30
            wb.save(path)
            logger.info("Exported with provenance sheet: %s", path)

        return path

    def export_transactions(self, transactions: list, filename: str = "transactions.xlsx",
                           language: str = 'en') -> str:
        """Export transactions to professionally styled Excel."""
        try:
            from openpyxl import Workbook
            from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
        except ImportError:
            raise RuntimeError("openpyxl not installed")

        tr = lambda text: self._tr(text, language)
        wb = Workbook()
        ws = wb.active
        ws.title = "Transactions"

        def fill(hex_color):
            return PatternFill("solid", fgColor=hex_color)
        def font(color=None, bold=False, size=10):
            return Font(color=color or self.DARK_TEXT, bold=bold, name="Calibri", size=size)
        thin = Border(
            bottom=Side(style="thin", color=self.BORDER_CLR),
            top=Side(style="thin", color=self.BORDER_CLR),
            left=Side(style="thin", color=self.BORDER_CLR),
            right=Side(style="thin", color=self.BORDER_CLR))

        headers = [tr("Date"), tr("Type"), tr("Department"), tr("Category"),
                  tr("Counterparty"), tr("Amount"), tr("VAT"),
                  tr("Acct Dr"), tr("Acct Cr")]
        col_widths = [14, 12, 24, 24, 32, 16, 12, 14, 14]
        for j, (h, w) in enumerate(zip(headers, col_widths)):
            ws.column_dimensions[chr(65 + j)].width = w
            c = ws.cell(row=1, column=j + 1, value=h)
            c.font = Font(color="FFFFFF", bold=True, name="Calibri", size=10)
            c.fill = fill(self.HEADER_BLUE)
            c.alignment = Alignment(horizontal="center", vertical="center")
            c.border = thin

        for i, t in enumerate(transactions):
            row = i + 2
            bg = self.LIGHT_GRAY if i % 2 == 0 else self.WHITE
            amt = t.get("amount", 0) or 0
            vals = [
                t.get("date", ""), t.get("type", "Expense"),
                t.get("dept", ""), t.get("cost_class", ""),
                t.get("counterparty", ""), amt,
                t.get("vat", 0) or 0,
                t.get("acct_dr", ""), t.get("acct_cr", ""),
            ]
            for j, v in enumerate(vals):
                c = ws.cell(row=row, column=j + 1, value=v)
                c.fill = fill(bg)
                c.border = thin
                if j == 5:  # amount
                    c.number_format = '#,##0;[Red](#,##0)'
                    c.font = font(self.GREEN_TEXT if amt >= 0 else self.RED_TEXT)
                    c.alignment = Alignment(horizontal="right")
                elif j == 6:  # vat
                    c.number_format = '#,##0'
                    c.font = font(self.MUTED_TEXT)
                    c.alignment = Alignment(horizontal="right")
                else:
                    c.font = font()

        # Freeze header + autofilter
        ws.freeze_panes = "A2"
        last = len(transactions) + 1
        ws.auto_filter.ref = f"A1:I{last}"

        # Print setup
        ws.page_setup.orientation = 'landscape'
        ws.page_setup.paperSize = ws.PAPERSIZE_A4
        ws.page_setup.fitToWidth = 1

        path = str(self.export_dir / filename)
        wb.save(path)
        return path

    def _fmt(self, v: float, currency: str = "GEL") -> str:
        sym = "₾" if currency == "GEL" else "$"
        if v is None:
            return "—"
        a = abs(v)
        if a >= 1e6:
            return f"{sym}{v / 1e6:.3f}M"
        if a >= 1e3:
            return f"{sym}{v / 1e3:.1f}K"
        return f"{sym}{v:.2f}"


excel_exporter = ExcelExporter(export_dir="./exports")
