"""
Phase I: Decision Intelligence Engine
======================================
Transforms diagnostic signals into ranked, simulated business actions.

Pipeline:
    DiagnosticReport -> ActionGenerator -> ImpactSimulator -> ActionRanker -> DecisionReport

Rules:
    - ALL financial math is deterministic (no LLM)
    - Actions derived from rule-based templates, never generated by AI
    - Impact simulated via existing financial_reasoning.simulate_scenario()
    - Composite scoring is a fixed, auditable formula

Reuses:
    - diagnosis_engine.DiagnosticReport  (input)
    - financial_reasoning.reasoning_engine.simulate_scenario()  (impact simulation)
"""

import logging
import math
import random
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════
# DATACLASSES
# ═══════════════════════════════════════════════════════════════════

@dataclass
class BusinessAction:
    """A concrete business action with simulated impact and risk assessment."""
    action_id: str
    description: str
    category: str           # cost_reduction|revenue_growth|risk_mitigation|capital_optimization|operational_efficiency
    expected_impact: float  # estimated P&L impact (positive = improvement)
    implementation_cost: float
    roi_estimate: float     # expected_impact / implementation_cost
    risk_level: str         # low|medium|high|critical
    time_horizon: str       # immediate|short_term|medium_term|long_term
    prerequisites: List[str] = field(default_factory=list)
    source_signal: str = ""
    composite_score: float = 0.0
    simulation_result: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action_id": self.action_id,
            "description": self.description,
            "category": self.category,
            "expected_impact": round(self.expected_impact, 2),
            "implementation_cost": round(self.implementation_cost, 2),
            "roi_estimate": round(self.roi_estimate, 2),
            "risk_level": self.risk_level,
            "time_horizon": self.time_horizon,
            "prerequisites": self.prerequisites,
            "source_signal": self.source_signal,
            "composite_score": round(self.composite_score, 4),
            "simulation_result": self.simulation_result,
        }


@dataclass
class RiskMatrix:
    """Actions grouped by risk level for visual risk assessment."""
    low_risk_actions: List[Dict[str, Any]] = field(default_factory=list)
    medium_risk_actions: List[Dict[str, Any]] = field(default_factory=list)
    high_risk_actions: List[Dict[str, Any]] = field(default_factory=list)
    critical_risk_actions: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "low_risk": self.low_risk_actions,
            "medium_risk": self.medium_risk_actions,
            "high_risk": self.high_risk_actions,
            "critical_risk": self.critical_risk_actions,
        }


@dataclass
class DecisionReport:
    """Complete decision intelligence output with ranked actions, risk matrix, and CFO verdict."""
    top_actions: List[BusinessAction] = field(default_factory=list)
    total_actions_evaluated: int = 0
    risk_matrix: RiskMatrix = field(default_factory=RiskMatrix)
    total_potential_impact: float = 0.0
    health_score_before: float = 0.0
    projected_health_score: float = 0.0
    cfo_verdict: Optional[Any] = None  # CFOVerdict (typed as Any to avoid forward ref)
    generated_at: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "top_actions": [a.to_dict() for a in self.top_actions],
            "total_actions_evaluated": self.total_actions_evaluated,
            "risk_matrix": self.risk_matrix.to_dict(),
            "total_potential_impact": round(self.total_potential_impact, 2),
            "health_score_before": round(self.health_score_before, 1),
            "projected_health_score": round(self.projected_health_score, 1),
            "cfo_verdict": self.cfo_verdict.to_dict() if self.cfo_verdict else None,
            "generated_at": self.generated_at,
        }


# ═══════════════════════════════════════════════════════════════════
# ACTION TEMPLATES — rule-based mapping from signals to actions
# ═══════════════════════════════════════════════════════════════════

# Key: (metric, direction) -> list of action templates
_ACTION_TEMPLATES: Dict[tuple, List[Dict[str, Any]]] = {
    # Revenue decline signals
    ("revenue", "down"): [
        {
            "description": "Launch targeted pricing review across product segments to recover revenue",
            "category": "revenue_growth",
            "base_cost": 50_000,
            "impact_pct": 0.03,  # 3% of revenue as potential recovery
            "risk": "medium",
            "horizon": "short_term",
            "prerequisites": ["Segment-level margin analysis", "Competitor pricing data"],
        },
        {
            "description": "Expand retail station network in high-demand regions",
            "category": "revenue_growth",
            "base_cost": 500_000,
            "impact_pct": 0.08,
            "risk": "high",
            "horizon": "long_term",
            "prerequisites": ["Market feasibility study", "Capital budget approval"],
        },
    ],
    # Gross margin compression
    ("gross_margin_pct", "down"): [
        {
            "description": "Renegotiate supplier contracts to reduce COGS by 2-5%",
            "category": "cost_reduction",
            "base_cost": 30_000,
            "impact_pct": 0.025,
            "risk": "low",
            "horizon": "short_term",
            "prerequisites": ["Supplier performance review"],
        },
        {
            "description": "Implement dynamic pricing model based on demand elasticity",
            "category": "revenue_growth",
            "base_cost": 100_000,
            "impact_pct": 0.04,
            "risk": "medium",
            "horizon": "medium_term",
            "prerequisites": ["Price elasticity analysis", "IT system upgrade"],
        },
        {
            "description": "Optimize product mix by increasing high-margin product share",
            "category": "operational_efficiency",
            "base_cost": 20_000,
            "impact_pct": 0.02,
            "risk": "low",
            "horizon": "short_term",
            "prerequisites": ["Product profitability analysis"],
        },
    ],
    # EBITDA decline
    ("ebitda", "down"): [
        {
            "description": "Conduct zero-based budgeting review on G&A expenses",
            "category": "cost_reduction",
            "base_cost": 40_000,
            "impact_pct": 0.015,
            "risk": "low",
            "horizon": "short_term",
            "prerequisites": ["Department cost breakdown"],
        },
        {
            "description": "Automate manual operational processes to reduce headcount costs",
            "category": "operational_efficiency",
            "base_cost": 200_000,
            "impact_pct": 0.05,
            "risk": "medium",
            "horizon": "medium_term",
            "prerequisites": ["Process audit", "Automation feasibility study"],
        },
    ],
    # Net profit decline
    ("net_profit", "down"): [
        {
            "description": "Restructure debt portfolio to reduce finance costs",
            "category": "capital_optimization",
            "base_cost": 25_000,
            "impact_pct": 0.02,
            "risk": "low",
            "horizon": "medium_term",
            "prerequisites": ["Debt maturity schedule review"],
        },
        {
            "description": "Optimize tax structure through available deductions and incentives",
            "category": "capital_optimization",
            "base_cost": 50_000,
            "impact_pct": 0.01,
            "risk": "low",
            "horizon": "short_term",
            "prerequisites": ["Tax advisor consultation"],
        },
    ],
    # G&A expenses rising
    ("ga_expenses", "up"): [
        {
            "description": "Implement strict procurement controls and vendor consolidation",
            "category": "cost_reduction",
            "base_cost": 15_000,
            "impact_pct": 0.01,
            "risk": "low",
            "horizon": "immediate",
            "prerequisites": ["Vendor list audit"],
        },
        {
            "description": "Reduce discretionary spending by 15% across departments",
            "category": "cost_reduction",
            "base_cost": 5_000,
            "impact_pct": 0.008,
            "risk": "low",
            "horizon": "immediate",
            "prerequisites": ["Budget freeze directive"],
        },
    ],
    # COGS rising
    ("cogs", "up"): [
        {
            "description": "Negotiate volume-based discounts with top 3 suppliers",
            "category": "cost_reduction",
            "base_cost": 20_000,
            "impact_pct": 0.03,
            "risk": "low",
            "horizon": "short_term",
            "prerequisites": ["Supplier concentration analysis"],
        },
        {
            "description": "Implement inventory optimization to reduce holding costs",
            "category": "operational_efficiency",
            "base_cost": 80_000,
            "impact_pct": 0.015,
            "risk": "medium",
            "horizon": "medium_term",
            "prerequisites": ["Inventory turnover analysis"],
        },
    ],
    # Liquidity warning
    ("current_ratio", "down"): [
        {
            "description": "Accelerate accounts receivable collection with early-payment discounts",
            "category": "capital_optimization",
            "base_cost": 10_000,
            "impact_pct": 0.01,
            "risk": "low",
            "horizon": "immediate",
            "prerequisites": ["AR aging report"],
        },
        {
            "description": "Negotiate extended payment terms with key suppliers",
            "category": "risk_mitigation",
            "base_cost": 5_000,
            "impact_pct": 0.005,
            "risk": "low",
            "horizon": "immediate",
            "prerequisites": ["AP aging report"],
        },
    ],
    # Net margin drop
    ("net_margin_pct", "down"): [
        {
            "description": "Perform comprehensive cost-to-serve analysis across channels",
            "category": "operational_efficiency",
            "base_cost": 60_000,
            "impact_pct": 0.025,
            "risk": "medium",
            "horizon": "medium_term",
            "prerequisites": ["Channel profitability data"],
        },
    ],
    # COGS ratio spike
    ("cogs_to_revenue_pct", "up"): [
        {
            "description": "Hedge commodity prices using forward contracts",
            "category": "risk_mitigation",
            "base_cost": 30_000,
            "impact_pct": 0.02,
            "risk": "medium",
            "horizon": "short_term",
            "prerequisites": ["Commodity exposure analysis", "Treasury approval"],
        },
    ],
}

# Fallback template for unmatched signals
_FALLBACK_TEMPLATE = {
    "description": "Conduct detailed variance analysis on {metric}",
    "category": "operational_efficiency",
    "base_cost": 15_000,
    "impact_pct": 0.01,
    "risk": "low",
    "horizon": "short_term",
    "prerequisites": ["Detailed metric breakdown"],
}


# ═══════════════════════════════════════════════════════════════════
# ACTION GENERATOR
# ═══════════════════════════════════════════════════════════════════

class ActionGenerator:
    """Generates BusinessAction instances from DiagnosticReport signals using rule templates."""

    # Maps action category to scenario simulation parameters
    _CATEGORY_SCENARIO_MAP = {
        "cost_reduction": {"ga_pct": -15},
        "revenue_growth": {"revenue_pct": 10},
        "capital_optimization": {"finance_expense_pct": -20},
        "operational_efficiency": {"cogs_pct": -5},
        "risk_mitigation": {"cogs_pct": -2},
    }

    def generate_actions(self, report, financials: Dict[str, float]) -> List[BusinessAction]:
        """
        Generate actions from diagnosis signals.

        Enhanced: computes ROI by running actual financial simulation for each action,
        not just template percentages.
        """
        actions: List[BusinessAction] = []
        revenue = financials.get("revenue", 0) or 0

        # Handle report as dict or object
        if isinstance(report, dict):
            diagnoses = report.get("diagnoses", report.get("signals", []))
        else:
            diagnoses = getattr(report, "diagnoses", [])

        for diagnosis in diagnoses:
            if isinstance(diagnosis, dict):
                signal = diagnosis.get("signal", diagnosis)
                if isinstance(signal, dict):
                    metric = signal.get("metric", "")
                    direction = signal.get("direction", "down")
                else:
                    metric = getattr(signal, "metric", "")
                    direction = getattr(signal, "direction", "down")
            else:
                signal = diagnosis.signal
                metric = signal.metric
                direction = signal.direction

            templates = _ACTION_TEMPLATES.get((metric, direction), [])

            if not templates:
                tmpl = _FALLBACK_TEMPLATE.copy()
                tmpl["description"] = tmpl["description"].format(metric=metric)
                templates = [tmpl]

            for tmpl in templates:
                # Base impact estimate from template
                template_impact = abs(revenue) * tmpl["impact_pct"] if revenue else 0
                cost = tmpl["base_cost"]

                # Try to compute actual ROI via simulation
                sim_result = self._compute_action_roi(
                    tmpl["category"], cost, financials
                )

                if sim_result and sim_result.get("data_driven"):
                    impact = sim_result["expected_impact"]
                    roi = sim_result["roi_estimate"]
                    sim_data = sim_result
                else:
                    impact = template_impact
                    roi = round(impact / max(cost, 1), 2)
                    sim_data = None

                action = BusinessAction(
                    action_id=f"{tmpl['category']}_{metric}_{uuid.uuid4().hex[:6]}",
                    description=tmpl["description"],
                    category=tmpl["category"],
                    expected_impact=round(impact, 2),
                    implementation_cost=cost,
                    roi_estimate=roi,
                    risk_level=tmpl["risk"],
                    time_horizon=tmpl["horizon"],
                    prerequisites=list(tmpl.get("prerequisites", [])),
                    source_signal=f"{metric}_{direction}_{signal.get('severity','medium') if isinstance(signal,dict) else getattr(signal,'severity','medium')}",
                    simulation_result=sim_data,
                )
                actions.append(action)

        return actions

    def _compute_action_roi(
        self, category: str, implementation_cost: float, financials: Dict[str, float],
    ) -> Optional[Dict[str, Any]]:
        """
        Compute ROI by actually running the scenario simulation.

        Returns dict with roi_estimate, expected_impact, simulation details,
        or None if simulation fails.
        """
        try:
            from app.services.financial_reasoning import reasoning_engine

            scenario_params = self._CATEGORY_SCENARIO_MAP.get(category, {"ga_pct": -10})

            base = {
                "revenue": financials.get("revenue", 0),
                "cogs": financials.get("cogs", 0),
                "gross_profit": financials.get("gross_profit", 0),
                "ga_expenses": financials.get("ga_expenses", 0),
                "depreciation": financials.get("depreciation", 0),
                "finance_expense": financials.get("finance_expense", 0),
                "tax_rate": financials.get("tax_rate", 0.15),
            }

            result = reasoning_engine.simulate_scenario(
                f"action_roi_{category}", base, scenario_params,
            )

            impact = result.scenario_net_profit - result.base_net_profit
            actual_roi = round(impact / max(implementation_cost, 1), 2)

            return {
                "roi_estimate": actual_roi,
                "expected_impact": round(impact, 0),
                "simulated_net_profit": round(result.scenario_net_profit, 0),
                "base_net_profit": round(result.base_net_profit, 0),
                "simulation_narrative": result.narrative,
                "scenario_params": scenario_params,
                "data_driven": True,
                "computed_from": "financial_reasoning.simulate_scenario",
            }
        except Exception as e:
            logger.debug("Action ROI simulation failed for %s: %s", category, e)
            return None


# ═══════════════════════════════════════════════════════════════════
# IMPACT SIMULATOR
# ═══════════════════════════════════════════════════════════════════

class ImpactSimulator:
    """Simulates the financial impact of a BusinessAction using the reasoning engine."""

    # Maps action category -> scenario change keys
    _CATEGORY_TO_CHANGES = {
        "cost_reduction": {"cogs_pct": -3.0, "ga_pct": -5.0},
        "revenue_growth": {"revenue_pct": 5.0},
        "risk_mitigation": {"cogs_pct": -1.0},
        "capital_optimization": {"finance_expense_pct": -10.0},
        "operational_efficiency": {"ga_pct": -8.0},
    }

    def simulate_action(self, action: BusinessAction, base_financials: Dict[str, float]) -> Dict[str, Any]:
        """
        Run scenario simulation for a single action.

        Returns:
            Dict with base/scenario comparison and ROI computation.
        """
        try:
            from app.services.financial_reasoning import reasoning_engine

            changes = self._build_changes(action)
            base = self._normalize_base(base_financials)

            result = reasoning_engine.simulate_scenario(
                scenario_name=action.description[:80],
                base=base,
                changes=changes,
            )

            base_np = result.base_net_profit
            scenario_np = result.scenario_net_profit
            delta = round(scenario_np - base_np, 2)
            roi = round(delta / max(action.implementation_cost, 1), 2)

            return {
                "scenario_name": result.scenario_name,
                "base_net_profit": round(base_np, 2),
                "scenario_net_profit": round(scenario_np, 2),
                "net_profit_delta": delta,
                "roi": roi,
                "risk_level": result.risk_level,
                "narrative": result.narrative,
            }
        except Exception as e:
            logger.warning("Impact simulation failed for %s: %s", action.action_id, e)
            return {
                "scenario_name": action.description[:80],
                "base_net_profit": base_financials.get("net_profit", 0),
                "scenario_net_profit": base_financials.get("net_profit", 0),
                "net_profit_delta": 0,
                "roi": 0,
                "risk_level": action.risk_level,
                "narrative": "Simulation unavailable",
            }

    def _build_changes(self, action: BusinessAction) -> Dict[str, float]:
        """Map action category + impact to scenario changes dict."""
        base_changes = self._CATEGORY_TO_CHANGES.get(action.category, {})
        changes = {}
        for key, default_pct in base_changes.items():
            # Scale by ROI — higher ROI actions get more aggressive changes
            scale = min(max(action.roi_estimate / 10.0, 0.5), 2.0)
            changes[key] = round(default_pct * scale, 2)
        return changes

    def _normalize_base(self, financials: Dict[str, float]) -> Dict[str, float]:
        """Ensure base dict has all keys required by simulate_scenario."""
        revenue = financials.get("revenue", 0)
        cogs = financials.get("cogs", 0)
        gp = financials.get("gross_profit", revenue - cogs)
        ga = financials.get("ga_expenses", 0)
        dep = financials.get("depreciation", 0)
        fin = financials.get("finance_expense", 0)
        tax = financials.get("tax_rate", 0.15)
        return {
            "revenue": revenue,
            "cogs": cogs,
            "gross_profit": gp,
            "ga_expenses": ga,
            "depreciation": dep,
            "finance_expense": fin,
            "tax_rate": tax,
        }


# ═══════════════════════════════════════════════════════════════════
# ACTION RANKER
# ═══════════════════════════════════════════════════════════════════

class ActionRanker:
    """Ranks actions by deterministic composite score."""

    _URGENCY_MAP = {"critical": 1.0, "high": 0.75, "medium": 0.5, "low": 0.25}
    _FEASIBILITY_MAP = {"immediate": 1.0, "short_term": 0.75, "medium_term": 0.5, "long_term": 0.25}
    _RISK_FACTOR_MAP = {"low": 1.0, "medium": 0.7, "high": 0.4, "critical": 0.2}

    # Weights: ROI matters most, then urgency, feasibility, risk adjustment
    W_ROI = 0.40
    W_URGENCY = 0.25
    W_FEASIBILITY = 0.20
    W_RISK = 0.15

    def rank_actions(self, actions: List[BusinessAction]) -> List[BusinessAction]:
        """
        Compute composite score and sort descending.

        Formula:
            composite = 0.40 * roi_norm + 0.25 * urgency + 0.20 * feasibility + 0.15 * risk_factor
        """
        if not actions:
            return actions

        # Normalize ROI to 0-1 range
        max_roi = max(abs(a.roi_estimate) for a in actions) or 1.0

        for action in actions:
            roi_norm = min(abs(action.roi_estimate) / max_roi, 1.0)

            # Extract severity from source_signal (format: metric_direction_severity)
            parts = action.source_signal.split("_")
            severity = parts[-1] if parts else "medium"
            urgency = self._URGENCY_MAP.get(severity, 0.5)

            feasibility = self._FEASIBILITY_MAP.get(action.time_horizon, 0.5)
            risk_factor = self._RISK_FACTOR_MAP.get(action.risk_level, 0.5)

            action.composite_score = round(
                self.W_ROI * roi_norm
                + self.W_URGENCY * urgency
                + self.W_FEASIBILITY * feasibility
                + self.W_RISK * risk_factor,
                4,
            )

        actions.sort(key=lambda a: a.composite_score, reverse=True)
        return actions


# ═══════════════════════════════════════════════════════════════════
# CFO VERDICT — the system makes THE call, not just lists options
# ═══════════════════════════════════════════════════════════════════

@dataclass
class SensitivityResult:
    """Monte Carlo sensitivity analysis for a single action."""
    action_id: str
    iterations: int
    mean_roi: float
    median_roi: float
    p10_roi: float          # 10th percentile (downside)
    p90_roi: float          # 90th percentile (upside)
    probability_positive: float  # % of runs with positive outcome
    worst_case_impact: float
    best_case_impact: float
    volatility: float       # std dev of outcomes

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action_id": self.action_id,
            "iterations": self.iterations,
            "mean_roi": round(self.mean_roi, 2),
            "median_roi": round(self.median_roi, 2),
            "p10_roi": round(self.p10_roi, 2),
            "p90_roi": round(self.p90_roi, 2),
            "probability_positive_pct": round(self.probability_positive * 100, 1),
            "worst_case_impact": round(self.worst_case_impact, 2),
            "best_case_impact": round(self.best_case_impact, 2),
            "volatility": round(self.volatility, 4),
        }


@dataclass
class CFOVerdict:
    """
    The system's opinionated, singular recommendation.

    This is NOT a list of options. This is THE decision.
    A CFO under pressure making the call with justification.
    """
    primary_action: Dict[str, Any]       # the #1 recommended action
    conviction_score: float              # 0-1: how confident the system is
    conviction_grade: str                # A+ / A / B+ / B / C / D / F
    verdict_statement: str               # one-sentence CFO-style directive
    justification: List[str]             # bullet-point reasoning
    risk_acknowledgment: str             # what could go wrong
    alternative_if_rejected: Optional[Dict[str, Any]] = None  # backup plan
    sensitivity: Optional[SensitivityResult] = None
    do_nothing_cost: float = 0.0         # estimated cost of inaction
    time_pressure: str = "normal"        # immediate|urgent|normal|can_wait
    generated_at: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "primary_action": self.primary_action,
            "conviction_score": round(self.conviction_score, 4),
            "conviction_grade": self.conviction_grade,
            "verdict_statement": self.verdict_statement,
            "justification": self.justification,
            "risk_acknowledgment": self.risk_acknowledgment,
            "alternative_if_rejected": self.alternative_if_rejected,
            "sensitivity": self.sensitivity.to_dict() if self.sensitivity else None,
            "do_nothing_cost": round(self.do_nothing_cost, 2),
            "time_pressure": self.time_pressure,
            "generated_at": self.generated_at,
        }


class MonteCarloSimulator:
    """
    Stress-tests an action across variable ranges using Monte Carlo simulation.

    All math is deterministic given a seed. No LLM.
    """

    _RISK_VOLATILITY = {"low": 0.15, "medium": 0.30, "high": 0.50, "critical": 0.70}

    def simulate(
        self,
        action: BusinessAction,
        base_financials: Dict[str, float],
        iterations: int = 1000,
        seed: int = 42,
    ) -> SensitivityResult:
        """
        Run Monte Carlo simulation for an action.

        Varies: implementation effectiveness (0.3x - 1.7x), cost overrun (1.0x - 1.5x),
        market conditions (-20% to +20% revenue shift).
        """
        rng = random.Random(seed)
        revenue = abs(base_financials.get("revenue", 1)) or 1
        volatility = self._RISK_VOLATILITY.get(action.risk_level, 0.30)

        outcomes: List[float] = []

        for _ in range(iterations):
            # Effectiveness varies: how much of expected impact is actually realized
            effectiveness = max(0.0, rng.gauss(1.0, volatility))

            # Cost overrun: implementation costs may exceed estimate
            cost_multiplier = max(1.0, rng.gauss(1.15, 0.15))

            # Market shift: external factors
            market_shift = rng.gauss(0.0, 0.05)  # +/- 5% std dev

            realized_impact = action.expected_impact * effectiveness * (1.0 + market_shift)
            actual_cost = action.implementation_cost * cost_multiplier

            net_outcome = realized_impact - actual_cost
            roi = net_outcome / max(actual_cost, 1)
            outcomes.append(roi)

        outcomes.sort()
        n = len(outcomes)
        mean_roi = sum(outcomes) / n
        median_roi = outcomes[n // 2]
        p10 = outcomes[int(n * 0.10)]
        p90 = outcomes[int(n * 0.90)]
        prob_positive = sum(1 for o in outcomes if o > 0) / n
        variance = sum((o - mean_roi) ** 2 for o in outcomes) / n
        std_dev = math.sqrt(variance)

        return SensitivityResult(
            action_id=action.action_id,
            iterations=iterations,
            mean_roi=mean_roi,
            median_roi=median_roi,
            p10_roi=p10,
            p90_roi=p90,
            probability_positive=prob_positive,
            worst_case_impact=round(outcomes[0] * action.implementation_cost, 2),
            best_case_impact=round(outcomes[-1] * action.implementation_cost, 2),
            volatility=std_dev,
        )


class ConvictionScorer:
    """
    Computes conviction — how strongly the system believes in its #1 pick.

    Factors:
        1. Composite score gap between #1 and #2 (bigger gap = more conviction)
        2. Monte Carlo probability of positive outcome
        3. Historical prediction accuracy (from PredictionTracker)
        4. Signal severity (more severe = more urgent = higher conviction to act)
        5. Risk-adjusted ROI consistency
    """

    _GRADE_THRESHOLDS = [
        (0.90, "A+"), (0.80, "A"), (0.70, "B+"), (0.60, "B"),
        (0.50, "C+"), (0.40, "C"), (0.30, "D"), (0.0, "F"),
    ]

    def score(
        self,
        top_action: BusinessAction,
        runner_up: Optional[BusinessAction],
        sensitivity: SensitivityResult,
        health_score: float,
    ) -> Tuple[float, str]:
        """
        Compute conviction score (0-1) and grade.

        Returns:
            (conviction_score, conviction_grade)
        """
        # Factor 1: Score dominance — how far ahead is #1 vs #2
        if runner_up and runner_up.composite_score > 0:
            dominance = min((top_action.composite_score - runner_up.composite_score)
                            / max(runner_up.composite_score, 0.01), 1.0)
        else:
            dominance = 1.0  # only one action = full dominance

        # Factor 2: Monte Carlo confidence
        mc_confidence = sensitivity.probability_positive

        # Factor 3: ROI strength (normalize: ROI of 5x = score 1.0)
        roi_strength = min(abs(top_action.roi_estimate) / 5.0, 1.0)

        # Factor 4: Urgency from health (worse health = higher conviction to act)
        urgency_from_health = max(0, (100.0 - health_score) / 100.0)

        # Factor 5: Low volatility = more predictable = higher conviction
        stability = max(0, 1.0 - sensitivity.volatility)

        # Weighted conviction
        conviction = (
            0.20 * dominance
            + 0.30 * mc_confidence
            + 0.20 * roi_strength
            + 0.15 * urgency_from_health
            + 0.15 * stability
        )
        conviction = round(min(max(conviction, 0.0), 1.0), 4)

        # Grade
        grade = "F"
        for threshold, g in self._GRADE_THRESHOLDS:
            if conviction >= threshold:
                grade = g
                break

        return conviction, grade


class VerdictBuilder:
    """
    Builds the CFO verdict: the opinionated, singular recommendation.

    This is the system acting as a CFO — it makes the call.
    """

    _TIME_PRESSURE_MAP = {
        "immediate": "immediate",
        "short_term": "urgent",
        "medium_term": "normal",
        "long_term": "can_wait",
    }

    _SEVERITY_URGENCY = {"critical": "immediate", "high": "urgent", "medium": "normal", "low": "can_wait"}

    def build_verdict(
        self,
        actions: List[BusinessAction],
        sensitivity: SensitivityResult,
        conviction: float,
        grade: str,
        health_score: float,
        financials: Dict[str, float],
    ) -> CFOVerdict:
        """Build the final CFO verdict from ranked actions + analysis."""
        if not actions:
            return CFOVerdict(
                primary_action={},
                conviction_score=0,
                conviction_grade="F",
                verdict_statement="Insufficient data to make a recommendation.",
                justification=["No actionable signals detected."],
                risk_acknowledgment="N/A",
                generated_at=datetime.now(timezone.utc).isoformat(),
            )

        top = actions[0]
        runner_up = actions[1] if len(actions) > 1 else None
        revenue = abs(financials.get("revenue", 1)) or 1

        # Build the verdict statement — direct, opinionated, CFO-style
        verdict = self._build_verdict_statement(top, conviction, grade, health_score)

        # Build justification bullets
        justification = self._build_justification(top, sensitivity, health_score, revenue)

        # Risk acknowledgment
        risk = self._build_risk_statement(top, sensitivity)

        # Do-nothing cost estimate
        do_nothing = self._estimate_inaction_cost(health_score, financials)

        # Time pressure
        severity_parts = top.source_signal.split("_")
        signal_severity = severity_parts[-1] if severity_parts else "medium"
        time_pressure = self._SEVERITY_URGENCY.get(signal_severity,
                        self._TIME_PRESSURE_MAP.get(top.time_horizon, "normal"))

        return CFOVerdict(
            primary_action=top.to_dict(),
            conviction_score=conviction,
            conviction_grade=grade,
            verdict_statement=verdict,
            justification=justification,
            risk_acknowledgment=risk,
            alternative_if_rejected=runner_up.to_dict() if runner_up else None,
            sensitivity=sensitivity,
            do_nothing_cost=do_nothing,
            time_pressure=time_pressure,
            generated_at=datetime.now(timezone.utc).isoformat(),
        )

    def _build_verdict_statement(self, action: BusinessAction, conviction: float,
                                  grade: str, health_score: float) -> str:
        """Generate the one-sentence CFO directive."""
        impact_str = f"{action.expected_impact:,.0f}" if action.expected_impact >= 1000 else f"{action.expected_impact:.0f}"

        if health_score < 30:
            urgency = "CRITICAL: Execute immediately"
        elif health_score < 50:
            urgency = "HIGH PRIORITY: Begin this week"
        elif health_score < 70:
            urgency = "RECOMMENDED: Schedule within 30 days"
        else:
            urgency = "ADVISORY: Consider at next planning cycle"

        return (
            f"{urgency} — {action.description}. "
            f"Expected impact: {impact_str} GEL at {action.roi_estimate:.1f}x ROI "
            f"({action.risk_level} risk). Conviction: {grade} ({conviction:.0%})."
        )

    def _build_justification(self, action: BusinessAction, sensitivity: SensitivityResult,
                              health_score: float, revenue: float) -> List[str]:
        """Build bullet-point reasoning for the recommendation."""
        bullets = []

        # ROI justification
        bullets.append(
            f"ROI of {action.roi_estimate:.1f}x ranks highest among "
            f"all evaluated actions (implementation cost: {action.implementation_cost:,.0f} GEL)"
        )

        # Monte Carlo backing
        bullets.append(
            f"Monte Carlo simulation ({sensitivity.iterations} runs): "
            f"{sensitivity.probability_positive*100:.0f}% probability of positive outcome, "
            f"median ROI {sensitivity.median_roi:.1f}x"
        )

        # Downside protection
        if sensitivity.p10_roi > 0:
            bullets.append(
                f"Even in the pessimistic scenario (P10), ROI remains positive at {sensitivity.p10_roi:.1f}x"
            )
        else:
            bullets.append(
                f"Downside risk: P10 scenario shows {sensitivity.p10_roi:.1f}x ROI — "
                f"implement risk controls before execution"
            )

        # Impact as % of revenue
        impact_pct = (action.expected_impact / revenue) * 100 if revenue else 0
        bullets.append(
            f"Expected impact of {action.expected_impact:,.0f} GEL represents "
            f"{impact_pct:.1f}% of current revenue"
        )

        # Health score context
        if health_score < 50:
            bullets.append(
                f"Current financial health score is {health_score:.0f}/100 — "
                f"inaction accelerates deterioration"
            )

        # Time horizon
        bullets.append(f"Time horizon: {action.time_horizon.replace('_', ' ')} — "
                        f"results expected within {self._horizon_to_months(action.time_horizon)}")

        return bullets

    def _build_risk_statement(self, action: BusinessAction, sensitivity: SensitivityResult) -> str:
        """Acknowledge what could go wrong."""
        if action.risk_level == "low":
            return (f"Low execution risk. Worst-case Monte Carlo scenario: "
                    f"{sensitivity.worst_case_impact:,.0f} GEL loss. "
                    f"Mitigate by starting with a pilot phase.")
        elif action.risk_level == "medium":
            return (f"Moderate execution risk. {(1-sensitivity.probability_positive)*100:.0f}% chance "
                    f"of negative outcome in simulation. Worst case: {sensitivity.worst_case_impact:,.0f} GEL. "
                    f"Require monthly progress reviews and kill switch at 60-day mark.")
        else:
            return (f"High execution risk. {(1-sensitivity.probability_positive)*100:.0f}% chance "
                    f"of negative outcome. Worst case: {sensitivity.worst_case_impact:,.0f} GEL. "
                    f"MANDATORY: Stage in phases, board approval required, weekly monitoring.")

    def _estimate_inaction_cost(self, health_score: float, financials: Dict[str, float]) -> float:
        """Estimate the cost of doing nothing — what deterioration continues."""
        revenue = abs(financials.get("revenue", 0))
        if health_score >= 80:
            return 0  # healthy — no penalty for inaction
        # Declining health = ongoing losses
        # Below 50: estimated 2% revenue at risk per quarter
        # Below 30: estimated 5% revenue at risk per quarter
        if health_score < 30:
            return round(revenue * 0.05, 2)
        elif health_score < 50:
            return round(revenue * 0.02, 2)
        elif health_score < 70:
            return round(revenue * 0.01, 2)
        return round(revenue * 0.005, 2)

    def _horizon_to_months(self, horizon: str) -> str:
        return {"immediate": "1-2 weeks", "short_term": "1-3 months",
                "medium_term": "3-6 months", "long_term": "6-12 months"}.get(horizon, "TBD")


# ═══════════════════════════════════════════════════════════════════
# DECISION ENGINE (ORCHESTRATOR)
# ═══════════════════════════════════════════════════════════════════

class DecisionEngine:
    """
    Orchestrates the full decision intelligence pipeline:
        DiagnosticReport -> Actions -> Simulations -> Ranking -> DecisionReport
    """

    def __init__(self):
        self.generator = ActionGenerator()
        self.simulator = ImpactSimulator()
        self.ranker = ActionRanker()
        self.monte_carlo = MonteCarloSimulator()
        self.conviction_scorer = ConvictionScorer()
        self.verdict_builder = VerdictBuilder()
        self._last_report: Optional[DecisionReport] = None
        self._last_verdict: Optional[CFOVerdict] = None

    def generate_decision_report(
        self,
        report,
        financials: Dict[str, float],
        top_n: int = 10,
    ) -> DecisionReport:
        """
        Full pipeline: generate -> simulate -> rank -> report.

        Args:
            report: DiagnosticReport from diagnosis_engine
            financials: Current P&L metrics
            top_n: Max number of top actions to return
        Returns:
            DecisionReport with ranked actions and risk matrix
        """
        try:
            # 1. Generate actions from signals
            actions = self.generator.generate_actions(report, financials)

            # 2. Simulate impact for each action
            for action in actions:
                sim = self.simulator.simulate_action(action, financials)
                action.simulation_result = sim
                # Update ROI from simulation if available
                if sim.get("roi", 0) != 0:
                    action.roi_estimate = sim["roi"]

            # 3. Rank actions
            actions = self.ranker.rank_actions(actions)

            # 4. Build risk matrix
            risk_matrix = self._build_risk_matrix(actions)

            # 5. Compute totals
            total_impact = sum(a.expected_impact for a in actions)
            projected = min(100.0, report.health_score + (total_impact / max(abs(financials.get("revenue", 1)), 1)) * 100)

            # 6. Generate CFO Verdict — the opinionated #1 recommendation
            verdict = self._generate_verdict(actions, report.health_score, financials)
            self._last_verdict = verdict

            result = DecisionReport(
                top_actions=actions[:top_n],
                total_actions_evaluated=len(actions),
                risk_matrix=risk_matrix,
                total_potential_impact=round(total_impact, 2),
                health_score_before=report.health_score,
                projected_health_score=round(projected, 1),
                cfo_verdict=verdict,
                generated_at=datetime.now(timezone.utc).isoformat(),
            )

            self._last_report = result
            logger.info("Decision report generated: %d actions, top composite=%.4f, verdict=%s (conviction=%s)",
                        len(actions), actions[0].composite_score if actions else 0,
                        verdict.conviction_grade, f"{verdict.conviction_score:.0%}")
            return result

        except Exception as e:
            logger.error("Decision report generation failed: %s", e)
            return DecisionReport(
                generated_at=datetime.now(timezone.utc).isoformat(),
            )

    def _generate_verdict(
        self,
        actions: List[BusinessAction],
        health_score: float,
        financials: Dict[str, float],
    ) -> CFOVerdict:
        """Generate the opinionated CFO verdict with Monte Carlo backing."""
        if not actions:
            return CFOVerdict(
                primary_action={},
                conviction_score=0,
                conviction_grade="F",
                verdict_statement="No actionable signals. Monitor and reassess next period.",
                justification=["No significant financial signals detected."],
                risk_acknowledgment="N/A",
                generated_at=datetime.now(timezone.utc).isoformat(),
            )

        top = actions[0]
        runner_up = actions[1] if len(actions) > 1 else None

        # Monte Carlo stress test on #1 pick
        sensitivity = self.monte_carlo.simulate(top, financials)

        # Conviction scoring
        conviction, grade = self.conviction_scorer.score(
            top, runner_up, sensitivity, health_score,
        )

        # Build the final verdict
        return self.verdict_builder.build_verdict(
            actions, sensitivity, conviction, grade, health_score, financials,
        )

    def get_last_report(self) -> Optional[DecisionReport]:
        """Return the most recently generated decision report."""
        return self._last_report

    def get_last_verdict(self) -> Optional[CFOVerdict]:
        """Return the most recently generated CFO verdict."""
        return self._last_verdict

    def _build_risk_matrix(self, actions: List[BusinessAction]) -> RiskMatrix:
        """Group actions by risk level."""
        matrix = RiskMatrix()
        for a in actions:
            summary = {"action_id": a.action_id, "description": a.description,
                        "roi": a.roi_estimate, "score": a.composite_score}
            if a.risk_level == "low":
                matrix.low_risk_actions.append(summary)
            elif a.risk_level == "medium":
                matrix.medium_risk_actions.append(summary)
            elif a.risk_level == "high":
                matrix.high_risk_actions.append(summary)
            else:
                matrix.critical_risk_actions.append(summary)
        return matrix

    def to_kg_entities(self) -> List[Dict[str, Any]]:
        """Generate KG-compatible entities for decision actions."""
        entities = []
        if not self._last_report:
            return entities
        for action in self._last_report.top_actions[:10]:
            entities.append({
                "entity_id": f"decision_{action.action_id}",
                "entity_type": "decision_action",
                "label_en": action.description[:80],
                "label_ka": "",
                "description": (
                    f"Category: {action.category}, ROI: {action.roi_estimate:.1f}x, "
                    f"Risk: {action.risk_level}, Horizon: {action.time_horizon}, "
                    f"Score: {action.composite_score:.4f}"
                ),
                "properties": {
                    "category": action.category,
                    "roi_estimate": action.roi_estimate,
                    "risk_level": action.risk_level,
                    "time_horizon": action.time_horizon,
                    "composite_score": action.composite_score,
                    "expected_impact": action.expected_impact,
                },
            })
        return entities


# Module-level singleton
decision_engine = DecisionEngine()
