"""add system of record tables - journal entries, posting lines, periods, audit trail

Revision ID: 3942c5d15eec
Revises: a4911698443f
Create Date: 2026-03-28 23:59:04.340438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3942c5d15eec'
down_revision: Union[str, None] = 'a4911698443f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_number_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_number_sequences', schema=None) as batch_op:
        batch_op.create_index('ix_docseq_prefix_year', ['prefix', 'fiscal_year'], unique=True)

    op.create_table('change_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_log_table_name'), ['table_name'], unique=False)
        batch_op.create_index('ix_changelog_record', ['table_name', 'record_id'], unique=False)
        batch_op.create_index('ix_changelog_table', ['table_name'], unique=False)
        batch_op.create_index('ix_changelog_time', ['changed_at'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('total_debit', sa.String(length=50), nullable=True),
    sa.Column('total_credit', sa.String(length=50), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('is_immutable', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index('ix_je_document', ['document_number'], unique=False)
        batch_op.create_index('ix_je_fiscal_year', ['fiscal_year'], unique=False)
        batch_op.create_index('ix_je_period', ['period'], unique=False)
        batch_op.create_index('ix_je_posting_date', ['posting_date'], unique=False)
        batch_op.create_index('ix_je_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_document_number'), ['document_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_journal_entries_period'), ['period'], unique=False)

    op.create_table('fiscal_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_name', sa.String(length=50), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_by', sa.Integer(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_je_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closing_je_id'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reopened_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_name')
    )
    with op.batch_alter_table('fiscal_periods', schema=None) as batch_op:
        batch_op.create_index('ix_fp_period', ['period_name'], unique=False)
        batch_op.create_index('ix_fp_status', ['status'], unique=False)
        batch_op.create_index('ix_fp_year', ['fiscal_year'], unique=False)

    op.create_table('posting_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=500), nullable=True),
    sa.Column('cost_center', sa.String(length=50), nullable=True),
    sa.Column('profit_center', sa.String(length=50), nullable=True),
    sa.Column('debit', sa.String(length=50), nullable=True),
    sa.Column('credit', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tax_code', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posting_lines', schema=None) as batch_op:
        batch_op.create_index('ix_pl_account', ['account_code'], unique=False)
        batch_op.create_index('ix_pl_cost_center', ['cost_center'], unique=False)
        batch_op.create_index('ix_pl_journal', ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posting_lines_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_posting_lines_cost_center'), ['cost_center'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posting_lines_cost_center'))
        batch_op.drop_index(batch_op.f('ix_posting_lines_account_code'))
        batch_op.drop_index('ix_pl_journal')
        batch_op.drop_index('ix_pl_cost_center')
        batch_op.drop_index('ix_pl_account')

    op.drop_table('posting_lines')
    with op.batch_alter_table('fiscal_periods', schema=None) as batch_op:
        batch_op.drop_index('ix_fp_year')
        batch_op.drop_index('ix_fp_status')
        batch_op.drop_index('ix_fp_period')

    op.drop_table('fiscal_periods')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_period'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_document_number'))
        batch_op.drop_index('ix_je_status')
        batch_op.drop_index('ix_je_posting_date')
        batch_op.drop_index('ix_je_period')
        batch_op.drop_index('ix_je_fiscal_year')
        batch_op.drop_index('ix_je_document')

    op.drop_table('journal_entries')
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.drop_index('ix_changelog_time')
        batch_op.drop_index('ix_changelog_table')
        batch_op.drop_index('ix_changelog_record')
        batch_op.drop_index(batch_op.f('ix_change_log_table_name'))

    op.drop_table('change_log')
    with op.batch_alter_table('document_number_sequences', schema=None) as batch_op:
        batch_op.drop_index('ix_docseq_prefix_year')

    op.drop_table('document_number_sequences')
    # ### end Alembic commands ###
