"""add knowledge graph persistence tables

Revision ID: a4911698443f
Revises: dfc859940600
Create Date: 2026-03-28 22:33:33.470996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4911698443f'
down_revision: Union[str, None] = 'dfc859940600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('label_en', sa.String(length=500), nullable=False),
    sa.Column('label_ka', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_entities', schema=None) as batch_op:
        batch_op.create_index('ix_kg_entity_dynamic', ['is_dynamic'], unique=False)
        batch_op.create_index('ix_kg_entity_type', ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_entities_entity_id'), ['entity_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_entities_entity_type'), ['entity_type'], unique=False)

    op.create_table('knowledge_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_entity_id', sa.String(length=200), nullable=False),
    sa.Column('target_entity_id', sa.String(length=200), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_relations', schema=None) as batch_op:
        batch_op.create_index('ix_kg_rel_source', ['source_entity_id'], unique=False)
        batch_op.create_index('ix_kg_rel_target', ['target_entity_id'], unique=False)
        batch_op.create_index('ix_kg_rel_type', ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_source_entity_id'), ['source_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_target_entity_id'), ['target_entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_relations_target_entity_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_relations_source_entity_id'))
        batch_op.drop_index('ix_kg_rel_type')
        batch_op.drop_index('ix_kg_rel_target')
        batch_op.drop_index('ix_kg_rel_source')

    op.drop_table('knowledge_relations')
    with op.batch_alter_table('knowledge_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_entities_entity_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_entities_entity_id'))
        batch_op.drop_index('ix_kg_entity_type')
        batch_op.drop_index('ix_kg_entity_dynamic')

    op.drop_table('knowledge_entities')
    # ### end Alembic commands ###
